name: loggme
description: "A litle package be relax when your apps are running on production. Always receive logs about what happen there through Telegram, slack and any other http REST API."

homepage: https://github.com/Ofceab-Studio/loggme
repository: https://github.com/Ofceab-Studio/loggme
version: 1.0.7

environment:
  sdk: '^3.0.0'
dependencies:
  auto_exporter: ^3.5.0
  dartz: ^0.10.1
  dotenv: ^4.2.0
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.8

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:  

scripts:
  gen-build: 'dart run build_runner build && mv lib/export.dart lib/loggme.dart'
  pub: "dart pub publish -y"